### ISSUE TITLE
Fix add trip view so that trip owner is automatically the current user

### ISSUE THREAD

**Issue by tjdolan121** [tjdolan121/3308_App#11]
Currently, the user specifies the trip owner when creating a trip.  Obviously this is not good...we want the current user to be automatically made the trip owner

**Comment by tjdolan121** [comment]
https://docs.djangoproject.com/en/3.0/topics/class-based-views/generic-editing/#models-and-request-user

**Comment by t-cochran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Any user can create and view the trips of other users.](https://trello.com/c/NcFvjdKT/68-any-user-can-create-and-view-the-trips-of-other-users)

**Comment by tjdolan121** [comment]
@t-cochran just noticed the issue you brought up.  I think they should be marked as separate issues so I will make a different issue for that
