### ISSUE TITLE
User should be able to control 'trip_status' after trip creation

### ISSUE THREAD

**Issue by srivardhansajja** [tjdolan121/3308_App#27]
This can be done with a button/drop-down beside each trip in Trip View Page to set the new status.
_[Work on this issue can only be started after trip_status field is enabled ( #26 )]_

**Comment by srivardhansajja** [comment]
Added a button beside each trip, but did not implement functionality to update status.
3 out of the 4 statuses can be automated, with relation to start date and end date, but we should give the user to dynamically select the status in case actual trip does not match with set date values (Ex: trip ends early, or trip goes on for longer, but is not an emergency)

**Comment by t-cochran** [comment]
> 3 out of the 4 statuses can be automated, with relation to start date and end date
I added this in pull request #38
