### ISSUE TITLE
Add emergency contact form

### ISSUE THREAD

**Issue by tjdolan121** [tjdolan121/3308_App#32]

**Comment by t-cochran** [comment]
I will work on this issue tomorrow, but I wondered about making emergency contacts a model:
<script src="https://gist.github.com/t-cochran/f7aa5490c6d8c07b453c91a3a587a881.js"></script>

**Why?**

- Let the user add/remove as many emergency contacts as they want (right now, there is only a single field for an emergency contact email and it is attached to our user model)
-Add more fields to the emergency contacts as we get further in the project (e.g. telephone number)

What do you guys think?

**Comment by t-cochran** [comment]
Closed #35 and created #39 which has the most recent changes on our master branch and a few additional features.

**Comment by t-cochran** [comment]
Closing this since #42 was merged.
