### ISSUE TITLE
Upcoming trips

### ISSUE THREAD

**Issue by srivardhansajja** [tjdolan121/3308_App#53]
I can only see 1 upcoming trip in Trip View page even though I am creating more, maybe they are not being created at all. This issue is not present with Past and In Progress trips

**Comment by t-cochran** [comment]
I checked this out and could not get the Trip View page to not display all the upcoming trips. They are all created and appear.

Database:
![image](https://user-images.githubusercontent.com/39935686/85973965-7c001c80-b991-11ea-8780-08d08a104b8a.png)

Trip view page:
![image](https://user-images.githubusercontent.com/39935686/85974013-95a16400-b991-11ea-9bff-9cc14043dce3.png)

Are the trips that you are adding within 7 days of the current date?

**Comment by t-cochran** [comment]
Closing this since we merged the fix in #54
